@startuml

skinparam class {
  BackgroundColor #ebebeb
  ArrowColor      #333
  BorderColor     #333
}

skinparam lineType ortho

package psr.container {
  interface ContainerInterface {
    + get(id_: typing.Union[str, type]) -> object
    + has(id_: typing.Union[str, type]) -> bool
  }
  interface ContainerExceptionInterface {}
  interface NotFoundExceptionInterface extends ContainerExceptionInterface {}

  ContainerInterface -- ContainerExceptionInterface : "raises >"
}

@enduml
